export {
  PR_STATES,
  VERDICT_COLORS,
  VERDICT_BG,
  CLAIM_VERDICT_COLORS,
  PROGRESS_STAGE_LABELS,
  SEVERITY_COLORS,
  SEVERITY_BG,
  FINDING_TYPE_LABELS,
  FINDING_TYPE_COLORS,
} from '@/lib/constants';
